export const ADMIN_ID_STRING = "adminId"
export const PAYER_ID_STRING = "payerId"
export const ONLINE_BACKE_END_PORT = "54.154.208.240"
// export const ONLINE_BACKE_END_PORT = "192.168.1.115"
// export const serverLive = "https://duma-payme-backend.herokuapp.com"
// export const CURRENCY = "currency"
// export const CUSTOMER_ID = "customerId"
// export const AMOUNT = "amount"
// export const CALLBACK_URL = "url"
export const API_PAYMENT_INIT =  `http://${ONLINE_BACKE_END_PORT}:3001/api/payment-init`
// export const API_DUMA_PAY_CLIENT_REDIRECT_INIT=`http://${ONLINE_BACKE_END_PORT}:3001/api/payment-redirect`
export const API_VALIDATE_PAYMENT_INTENT = `http://${ONLINE_BACKE_END_PORT}:3001/api/validate`
export const API_CREATE_PAYMENT_INTENT = `http://${ONLINE_BACKE_END_PORT}:3001/api/create-payment-intent`
// export const API_RETRIEVE_PURCHASED_OBJECT = `http://${ONLINE_BACKE_END_PORT}:3001/api/payment`
export const DEBIT_CARD = "debit card"
export const MOBILE_MONEY = "mobile money"
export const EDIT_FORM_VALUES = 'editFormValue'
export const FORM_EMPTY_VALUES ="emptyFormValues"
export const CHANGE_MODAL_STATES = "changeModalState"
// export const SENDER_NAME = "name"
// export const SENDER_EMAIL = "email"
// export const SENDER_PHONE_NUMBER = "phone"
// export const CURRENCY = "currency"
// export const RATE = "rate"
// export const FEES = "fees"
// export const AMOUNT_TO_SEND = "amount"
// export const TOTAL_TO_PAY = "total"
// export const RECEIVER_NAME ="receiverName"
export const SHOW_SUCCESS_MODAL = "showsuccessmodal"
export const SHOW_FAIL_MODAL = "showfailmodal"
export const SHOW_PENDING_MODAL = "showpendingmodal"
export const SUCCEEDED ="succeeded"
